{{- $globconfig := .Files.Glob "data/config.toml" }}
{{- if $globconfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config_name }}
  namespace: {{ .Release.Namespace }}
data:
  terrascan-config: |-
{{ .Files.Get "data/config.toml" | indent 4 }}
{{- end }}
