apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --branch=master
            - https://github.com/accurics/terrascan.git
            - /data
          volumeMounts:
            - mountPath: /data
              name: terrascan-data-sync
      containers:
        - name: terrascan-server
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false
          image: {{ .Values.terrascan_container_image }}
          command:
            - terrascan
          args:
            - "server"
            - "--cert-path"
            - "/etc/certs/cert"
            - "--key-path"
            - "/etc/certs/key"
{{- if .Values.use_debug }}
            - "-l"
            - "debug"
{{- end }}
{{- $globconfig := .Files.Glob "data/config.toml" }}
{{- if $globconfig }}
            - "-c"
            - "/etc/config/terrascan-config"
{{- end }}
          env:
            - name: "K8S_WEBHOOK_API_KEY"
              value: {{ .Values.terrascan_webhook_key}}
          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs
            - name: ssh-volume
              mountPath: /home/terrascan/.ssh
{{- $globconfig := .Files.Glob "data/config.toml" }}
{{- if $globconfig }}
            - name: config-volume
              mountPath: /etc/config
{{- end }}
            - name: terrascan-data-sync
              mountPath: /home/terrascan/.terrascan
      volumes:
        - name: cert-volume
          secret:
            secretName: {{ .Values.cert_secret_name }}
        - name: ssh-volume
          secret:
            secretName: {{ .Values.ssh_secret_name }}
            optional: true
{{- $globconfig := .Files.Glob "data/config.toml" }}
{{- if $globconfig }}
        - name: config-volume
          configMap:
            name: {{ .Values.config_name }}
{{- end }}
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: terrascan-data-sync
          persistentVolumeClaim:
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else }}
        - name: terrascan-data-sync
          emptyDir: {}
{{- end }}
{{- if .Values.webhook.mode }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}
webhooks:
  - name: {{ .Values.webhook.name }}
    admissionReviewVersions:
    {{- range .Values.webhook.admissionReviewVersions }}
    - {{ . | printf "%s" }}
    {{ end }}
    failurePolicy: Ignore
    sideEffects: {{ .Values.webhook.sideEffects }}
    clientConfig:
      service:
        name: {{ .Values.name }}
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.terrascan_webhook_key | printf "/v1/k8s/webhooks/%s/scan/validate" }}
      caBundle: {{ .Files.Get "data/server.crt" | b64enc }}
    rules:
      - apiGroups:
        {{- range .Values.webhook.apiGroups }}
        {{- if eq . ""}}
        - ""
        {{- else if eq . "*" }}
        - "*"
        {{- else }}
        - {{ . -}}
        {{- end }}
        {{- end }}
        resources:
        {{- range .Values.webhook.resources }}
        {{- if eq . ""}}
        - ""
        {{- else if eq . "*" }}
        - "*"
        {{- else }}
        - {{ . -}}
        {{- end }}
        {{- end }}
        apiVersions:
        {{- range .Values.webhook.apiVersions }}
        {{- if eq . ""}}
        - ""
        {{- else if eq . "*" }}
        - "*"
        {{- else }}
        - {{ . -}}
        {{- end }}
        {{- end }}
        operations:
        {{- range .Values.webhook.operations }}
        {{- if eq . ""}}
        - ""
        {{- else if eq . "*" }}
        - "*"
        {{- else }}
        - {{ . -}}
        {{- end }}
        {{- end }}
{{- end }}
