 repos:
 # The below repo is configured for local testing purposes
 # to test you can run the following command:
 # `pre-commit run -v --files tests/infrastructure/success/main.tf`
 -  repo: local
    hooks:
    -   id: terrascan
        name: terrascan
        entry: terrascan
        language: python
        types: [terraform]
        pass_filenames: false
        args: [-l=tests/infrastructure/success/]
        verbose: true
# Here's an example on how to setup terrascan as a pre-commit
#-   repo: https://github.com/cesar-rodriguez/terrascan
#    rev: v0.1.2
#    hooks:
#    -   id: terrascan
#        pass_filenames: false
#        args: [-l=<LOCATION>] ##NOTE: this needs to be changed to reference the location of your terraform files
#        verbose: true
