# Project Info
site_name: Terrascan documentation
site_description: >-
  Detect compliance and security violations across Infrastructure as Code to mitigate risk before deploying cloud native infrastructure.
copyright:  >-
  &copy; 2020 Accurics, Inc. All rights reserved. Terrascan and Terrascan logo are US trademarks of Accurics Inc. All other registered trademarks are the properties of their respective owners.

# Repository
repo_name: accurics/terrascan
repo_url: https://github.com/accurics/terrascan/

# Configuration
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/terrascan-icon-white.png
  custom_dir: docs/overrides
  palette:
    primary: green
  language: en

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Social Icons
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AccuricsSec
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/accurics
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/accuricsorg
    - icon: fontawesome/brands/github
      link: https://github.com/accurics

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Policies:
    - Policy Reference: policies.md
    - AWS: policies/aws.md
    - GCP: policies/gcp.md
    - Azure: policies/azure.md
    - GitHub: policies/github.md
  # - Educational Resources: learning.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - About: about.md

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true

google_analytics:
  - UA-XXXXXXXX-X
  - auto

# Plugins
plugins:
  - diagrams
  - search

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
