terrascan_api_key: terrakey
terrascan_container_image: accurics/terrascan:1.6.0
use_debug: true
cert_secret_name: terrascancerts
ssh_secret_name: terrascanssh
config_name: terrascanconfig
name: terrascan
persistence:
  enabled: false
  existingclaim: terrascanPvc
