{{- if eq .Values.webhook.failurePolicy "Fail" }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook": "post-install"
webhooks:
  - name: {{ .Values.webhook.name }}
    admissionReviewVersions:
    {{- range .Values.webhook.admissionReviewVersions }}
    - {{ . | printf "%s" }}
    {{ end }}
    failurePolicy: Fail
    sideEffects: {{ .Values.webhook.sideEffects }}
    clientConfig:
      service:
        name: {{ .Values.name }}
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.terrascan_webhook_key | printf "/v1/k8s/webhooks/%s/scan/validate" }}
      caBundle: {{ .Files.Get "data/server.crt" | b64enc }}
    rules:
      - apiGroups:
        {{- range .Values.webhook.apiGroups }}
        {{- if eq . ""}}
        - ""
        {{- else if eq . "*" }}
        - "*"
        {{- else }}
        - {{ . -}}
        {{- end }}
        {{- end }}
        resources:
        {{- range .Values.webhook.resources }}
        {{- if eq . ""}}
        - ""
        {{- else if eq . "*" }}
        - "*"
        {{- else }}
        - {{ . -}}
        {{- end }}
        {{- end }}
        apiVersions:
        {{- range .Values.webhook.apiVersions }}
        {{- if eq . ""}}
        - ""
        {{- else if eq . "*" }}
        - "*"
        {{- else }}
        - {{ . -}}
        {{- end }}
        {{- end }}
        operations:
        {{- range .Values.webhook.operations }}
        {{- if eq . ""}}
        - ""
        {{- else if eq . "*" }}
        - "*"
        {{- else }}
        - {{ . -}}
        {{- end }}
        {{- end }}
{{- end -}}