name: Go Terrascan build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPATH: /home/runner/work/terrascan
      GOBIN: /home/runner/work/terrascan/bin
    steps:
    - name: Checkout Terrascan
      uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Install golint
      run: |
        go get -u golang.org/x/lint/golint
    - name: Go validations
      run: |
        echo Workflow trigger - ${{ github.event_name }}
        make validate
    - name: Build Terrascan
      run: |
        make build
    - name: Run unit tests
      run: |
        make unit-tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
